var age;
age = 28;
console.log(age);
var fullname;
fullname = 'Nagy József';
console.log(fullname);
var joido;
joido = true;
console.log(joido);
var nums = [];
var a;
a = 35;
a = 'asd';
a = false;
var nums = [];
nums.push(35);
nums.push(45);
nums.push(55);
console.log(nums[0]);
var names = [];
names.push('József');
var numTuple = [34, 55, 'aa'];
